version: 1.0.{build}
image: WMF 5
install:
- ps: >-
    $gitData = ConvertFrom-StringData (git log -1 --format=format:"commitId=%H%nmessage=%s%ncommitted=%aD" | out-string)
    
    if ($gitData['message'] -eq "") { $gitData['message'] = "No commit message available for $($gitData['commitid'])" }
    
    Update-AppveyorBuild @gitData
build_script:
- ps: >-
    gci * -filter *.ps1
    
    $firstScript = gci * -filter *.ps1 | Select -Expand Name -First 1 
    
    & ./$firstScript
test: off